name: Deploy Metabase Staging

on:
  workflow_run:
    workflows: ["Serialization Test"]
    branches: ["*DEPLOY-VERSION*"]
    types:
      - completed

jobs:
  deploy_metabase_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Debug Branch Name
        run: |
          echo "Branch name is: ${{ github.event.workflow_run.head_branch }}"

      - name: Run Export Script
        id: export
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}
          ENDPOINT_URL: ${{ vars.STAGING_ENDPOINT_URL }}
          COLLECTION: ${{ vars.DEFAULT_COLLECTION }}
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "Running Export Script on branch: $BRANCH"
          go run main.go export \
            endpoint_url=$ENDPOINT_URL \
            api_key=$API_KEY \
            collection=$COLLECTION

      - name: Commit and Push Exported Files
        if: ${{ steps.export.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Preparing to commit and push exported serialization..."
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
        
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add exported serialization from $BRANCH"
          fi

          git fetch origin main
          git checkout main

          git merge "$BRANCH" --no-ff -m "Merge changes from $BRANCH"
          git push origin main

      - name: Delete Branch After Merge
        if: ${{ steps.export.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "Deleting branch: $BRANCH"
          if [[ "$BRANCH" == "main" ]]; then
            echo "Not deleting the main branch."
          else
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH"
          fi
