name: Deploy Metabase Staging

on:
  push:
    branches:
      - '*DEPLOY-VERSION'

jobs:
  deploy_metabase_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: 'repo'

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run Export Script
        working-directory: ./repo
        env:
          API_KEY: ${{ secrets.METABASE_STAGING_API_KEY }}
          ENDPOINT_URL: ${{ vars.METABASE_STAGING_ENDPOINT_URL }}
          COLLECTION: ${{ vars.DEFAULT_COLLECTION }}
        run: |
          go run main.go export \
            endpoint_url=$ENDPOINT_URL \
            api_key=$API_KEY \
            collection=$COLLECTION

      - name: Create and checkout new branch
        id: create_branch
        working-directory: ./repo
        run: |
          DEPLOY_BRANCH="${GITHUB_REF##*/}"
          TEMP_BRANCH="export-${DEPLOY_BRANCH}-$(date +%s)"
          git checkout -b $TEMP_BRANCH
          echo "temp_branch=$TEMP_BRANCH" >> $GITHUB_OUTPUT
          echo "deploy_branch=$DEPLOY_BRANCH" >> $GITHUB_OUTPUT

      - name: Commit changes to temp branch
        working-directory: ./repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add .
          
          if ! git diff --cached --quiet; then
            git commit -m "Add exported serialization from ${{ steps.create_branch.outputs.deploy_branch }}"
            git push origin ${{ steps.create_branch.outputs.temp_branch }}
          else
            echo "No changes to commit."
            exit 1
          fi

      - name: Create Pull Request to Main
        id: create-pr
        working-directory: ./repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr create \
            --base main \
            --head "${{ steps.create_branch.outputs.temp_branch }}" \
            --title "Export updates to Main" \
            --body "Automated export of Metabase serialization
            
            Changes exported from branch: ${{ steps.create_branch.outputs.deploy_branch }}
            Exported at: $(date)")
          
          echo "Pull Request URL: $PR_URL"
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT

      - name: Delete original DEPLOY-VERSION branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ steps.create_branch.outputs.deploy_branch }}" == "main" ]]; then
            echo "Not deleting the main branch."
          else
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ steps.create_branch.outputs.deploy_branch }}"
          fi

      - name: Output PR Link
        run: |
          echo "🔗 Pull Request created. Please review and approve: ${{ steps.create-pr.outputs.pr_url }}"