name: Deploy Metabase Staging

on:
  push:
    branches:
      - '*DEPLOY-VERSION'

jobs:
  deploy_metabase_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run Export Script
        env:
          API_KEY: ${{ secrets.METABASE_STAGING_API_KEY }}
          ENDPOINT_URL: ${{ vars.METABASE_STAGING_ENDPOINT_URL }}
          COLLECTION: ${{ vars.DEFAULT_COLLECTION }}
        run: |
          go run main.go export \
            endpoint_url=$ENDPOINT_URL \
            api_key=$API_KEY \
            collection=$COLLECTION

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add .
          
          if ! git diff --cached --quiet; then
            git commit -m "Add exported serialization from ${GITHUB_REF##*/}"
            git push origin ${GITHUB_REF##*/}
          else
            echo "No changes to commit."
            exit 1
          fi

      - name: Create Pull Request to Main
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH="${GITHUB_REF##*/}"
          
          PR_URL=$(gh pr create \
            --base main \
            --head "$CURRENT_BRANCH" \
            --title "Export updates to Main from $CURRENT_BRANCH" \
            --body "Automated export of Metabase serialization
            
            Changes exported from branch: $CURRENT_BRANCH
            Exported at: $(date)")
          
          echo "Pull Request URL: $PR_URL"
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT

      - name: Output PR Link
        run: |
          echo "🔗 Pull Request created. Please review and approve: ${{ steps.create-pr.outputs.pr_url }}"