name: Deploy Metabase Production

on:
  release:
    types: [published]

jobs:
  deploy_metabase_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run Import Script
        if: success()
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}
          ENDPOINT_URL: ${{ vars.STAGING_ENDPOINT }}
        run: |
          echo "Running Import Script..."
          echo "Endpoint URL: $ENDPOINT_URL"
          echo "API Key: $API_KEY"
          go run main.go import \
            endpoint_url=$ENDPOINT_URL \
            api_key=$API_KEY