name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      STAGING_ENDPOINT_URL: ${{ vars.STAGING_ENDPOINT_URL }}
      STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
      TEST_COLLECTION_ID: ${{ vars.TEST_COLLECTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run Integration Tests
        run: go test -v ./...